<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            margin: 0;
            padding: 20px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        
        .header h1 {
            margin: 0;
            font-size: 18px;
            color: #333;
        }
        
        .meta-info {
            margin-bottom: 20px;
            background-color: #f8f9fa;
            padding: 10px;
            border-radius: 4px;
        }
        
        .meta-info p {
            margin: 5px 0;
            font-size: 11px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        
        th {
            background-color: #f2f2f2;
            font-weight: bold;
            font-size: 11px;
        }
        
        td {
            font-size: 10px;
        }
        
        .text-right {
            text-align: right;
        }
        
        .text-center {
            text-align: center;
        }
        
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            height: 50px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        
        .page-number:before {
            content: "Page " counter(page);
        }
        
        @page {
            margin: 100px 50px 80px 50px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
    </div>

    <div class="meta-info">
        <p><strong>Generated:</strong> {{ $result->generated_at }}</p>
        @if(isset($result->meta['date_range']))
        <p><strong>Date Range:</strong> {{ $result->meta['date_range']['from'] }} to {{ $result->meta['date_range']['to'] }}</p>
        @endif
        <p><strong>Total Rows:</strong> {{ $result->meta['total_rows'] ?? count($result->rows) }}</p>
        @if(isset($result->meta['truncated']) && $result->meta['truncated'])
        <p style="color: #dc3545;"><strong>Note:</strong> Results have been truncated to the maximum allowed rows.</p>
        @endif
    </div>

    @if(count($result->rows) > 0)
    <table>
        <thead>
            <tr>
                @foreach($result->columns as $column)
                <th class="{{ $column['type'] === 'currency' || $column['type'] === 'integer' || $column['type'] === 'number' ? 'text-right' : '' }}">
                    {{ $column['label'] }}
                </th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($result->rows as $row)
            <tr>
                @foreach($result->columns as $column)
                <td class="{{ $column['type'] === 'currency' || $column['type'] === 'integer' || $column['type'] === 'number' ? 'text-right' : '' }}{{ $column['type'] === 'date' ? 'text-center' : '' }}">
                    {{ $row[$column['key']] ?? '' }}
                </td>
                @endforeach
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div style="text-align: center; padding: 40px; color: #666;">
        <p>No data available for the selected criteria.</p>
    </div>
    @endif

    <div class="footer">
        <p>Generated by HotspotPortal Reporting System | <span class="page-number"></span></p>
    </div>
</body>
</html>