ALERT: {{ $message->title }}

Severity: {{ $message->severity->label() }}
Code: {{ $message->code }}
Time: {{ $message->occurredAt->format('Y-m-d H:i:s T') }}

Details:
{{ $message->body }}

@if(!empty($message->context))
Context:
@foreach($message->context as $key => $value)
- {{ $key }}: {{ is_string($value) ? $value : json_encode($value) }}
@endforeach
@endif

--
This alert was generated by Hotspot Portal